# Generated by Django 5.0.3 on 2024-03-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderregister',
            name='email',
        ),
        migrations.RemoveField(
            model_name='riderregister',
            name='password',
        ),
        migrations.RemoveField(
            model_name='riderregister',
            name='username',
        ),
    ]
