# Generated by Django 5.0.3 on 2024-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_remove_riderregister_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderregister',
            name='licenseImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
