# Generated by Django 5.0.3 on 2024-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_riderregister_licenseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderregister',
            name='licenseImage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
