# Generated by Django 5.0.3 on 2024-03-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_alter_riderregister_licenseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderregister',
            name='licenseImage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
